CREATE TABLE IF NOT EXISTS past_leaders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  position VARCHAR(100) NOT NULL,
  term_start YEAR NOT NULL,
  term_end YEAR NOT NULL,
  photo VARCHAR(255),
  achievements TEXT,
  order_priority INT DEFAULT 0,
  is_active TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

