export { default as ClubsPage } from './ClubsPage';
export { default as EventsPage } from './EventsPage';
export { default as HistoryPage } from './HistoryPage';
export { default as HomePage } from './HomePage';
export { default as MagnaCartaPage } from './MagnaCartaPage';
export { default as MemberSearchPage } from './MemberSearchPage';
export { default as NewsPage } from './NewsPage';
export { default as OfficersPage } from './OfficersPage';
export { default as VideosPage } from './VideosPage';
